export const COLOR_EXTENSION_MAP: { [key: string]: string } = {
  pdf: "red",
  doc: "blue",
  docx: "blue",
  xls: "green",
  xlsx: "green",
  ppt: "orange",
  pptx: "orange",
  jpg: "purple",
  jpeg: "purple",
  png: "purple",
  gif: "purple",
  svg: "purple",
  mp4: "pink",
  mov: "pink",
  mp3: "black",
  mpeg: "black",
  wav: "black",
  txt: "grey",
  zip: "brown",
  rar: "brown",
  "7z": "brown",
  tar: "brown",
  gz: "brown",
  plain: "grey",
  "": "grey",
};
